### ISSUE TITLE
Website To-Do List

### ISSUE THREAD

**Issue by alilies** [wluo2011/sharedwithlove#3]
# **Features We Need to Build on Top of Shopify theme**

1) Non-Readily Available in Current Theme (Boundless)*

Should look at some paid shopify themes online to see if this is easier to build with another default theme before trying to build myself.

- [ ] Customize Product Search filtered by Size, Dates Available, Color and Occassion
- Need to show filters, currently you can already search by keywords
- [ ] Uploading Page for "Sharers" **
- [ ] Comments 
- [ ] Reviews
- [ ] Upload photos for comments
- [ ] Import Instagram handle 
- [ ] Changing Multiple Image Displays

* not tied to this theme, but is most easily usable for our needs right now
** need to think of a better name for people who are renting out their dresses other than sharers and renters

2) Currently Available (Copy-Related)
- [ ] E-mail Templates (#2)
- [ ] Upload Products
- Descriptions
- Images
- [ ] Descriptions for How to Share & How to Rent
- [ ] Checkout Copy
- [ ] Homepage Copy
- [ ] About Us Copy
- [ ] FAQ (Guarantee, Insurance, Shipping & Delivery) Copy

**Comment by alilies** [comment]
@wluo2011 
I leave you to the things in Part 2? You can create separate tickets with these things or assign them to me and we can write sample copy and approve of each other's choices or give feedback/other options.
